name: CI - test and linting automation

on:
  push:
    branches: [ main, jest ]
  pull_request:
    branches: [ main, jest ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./server
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v.14
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    # Install dependencies
    - run: npm ci
      working-directory: ${{ env.working-directory }}
    - run: npm test
      working-directory: ${{ env.working-directory }}