name: CI - test and linting automation

on:
  push:
    branches: [ main, jest ]
  pull_request:
    branches: [ main, jest ]


env: 
  working-directory: ./server

jobs:
  tests:
    name: CI - Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v.14
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    # Install dependencies
    - run: npm ci
      working-directory: ${{ env.working-directory }}
    - run: npm test
      working-directory: ${{ env.working-directory }}
    - name: Test job context
      if: always()
      env:
        JOBS_CONTEXT: ${{ toJSON(job) }}
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT, $JOBS_CONTEXT"
  linting:
    name: CI - Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v.14
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    # Install dependencies
    - run: npm ci
      working-directory: ${{ env.working-directory }}
    - run: npm run lint
      working-directory: ${{ env.working-directory }}
    - name: Linting job context
      if: always()
      env:
        JOBS_CONTEXT: ${{ toJSON(job) }}
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT, $JOBS_CONTEXT"